<h2 style = "color : Brown"> Operations on NumPy Arrays</h2>

The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


In [1]:
import numpy as np

<h4 style = "color : Sky blue"> Example - 1 (Arithmatric Operations)</h4>  


In [2]:
array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)

In [3]:
array1

array([10, 20, 30, 40, 50])

In [4]:
array2

array([0, 1, 2, 3, 4])

In [5]:
# Add array1 and array2.
array3 = array1 + array2

In [6]:
array3

array([10, 21, 32, 43, 54])

<h4 style = "color : Sky blue"> Example - 2</h4>  

In [7]:
array4 = np.array([1,2,3,4])

In [8]:
array4 + array1

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [9]:
print (array1.shape)

(5,)


In [10]:
print (array4.shape)

(4,)


<h4 style = "color : Sky blue"> Example - 3</h4>  

In [11]:
array = np.linspace(1, 10, 5)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
array*2

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [13]:
array**2

array([  1.    ,  10.5625,  30.25  ,  60.0625, 100.    ])

<h4 style = "color : Sky blue"> Stacking Arrays</h4> 

####  ```np.hstack()``` and ```n.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

In [14]:
# Note that np.hstack(a, b) throws an error - you need to pass the arrays as a list
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [15]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
array1 = np.arange(12).reshape(3,4) #3x4
array2 = np.arange(20).reshape(5,4) #5x4

In [19]:
print (array1, '\n', array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [20]:
np.vstack((array1,array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

<h4 style = "color : Sky blue"> Example - 4 (Numpy Built-in functions)</h4>  

In [21]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.power(array1, 3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [23]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
x = np.array([-2,-1, 0, 1,2])
x

array([-2, -1,  0,  1,  2])

In [25]:
abs(x)

array([2, 1, 0, 1, 2])

In [26]:
np.absolute(x)

array([2, 1, 0, 1, 2])

<h4 style = "color : Sky blue"> Example - 5 (Trignometric functions)</h4>  

In [27]:
np.pi

3.141592653589793

In [28]:
theta = np.linspace(0, np.pi, 5)

In [29]:
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [30]:
np.sin(theta)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [31]:
np.cos(theta)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [32]:
np.tan(theta)

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16])

<h4 style = "color : Sky blue"> Example - 6 (Exponential and logarithmic functions)</h4>  

In [33]:
x = [1, 2, 3, 10]
x = np.array(x)

In [34]:
np.exp(x) # e=2.718...

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 2.20264658e+04])

In [35]:
# 2^1, 2^2, 2^3, 2^10
np.exp2(x)

array([   2.,    4.,    8., 1024.])

In [36]:
np.power(x,3)

array([   1,    8,   27, 1000])

In [37]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 2.30258509])

In [38]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 3.32192809])

In [39]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 1.        ])

In [40]:
np.log

<ufunc 'log'>

<h4 style = "color : Sky blue"> Example - 7</h4>  

In [41]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [42]:
y = x * 10
y

array([ 0, 10, 20, 30, 40])

In [43]:
y = np.empty(5)
y

array([0.00000000e+000, 9.54652321e-312, 9.54659122e-312, 9.54659123e-312,
       9.54661787e-312])

In [44]:
np.multiply(x, 12, out=y)

array([ 0., 12., 24., 36., 48.])

In [45]:
y

array([ 0., 12., 24., 36., 48.])

In [46]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [48]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

<h4 style = "color : Sky blue"> Example - 8 (Aggregates)</h4>  

In [49]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [50]:
sum(x)

np.int64(15)

In [51]:
np.add.reduce(x)

np.int64(15)

In [52]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [53]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

#### Apply Basic Linear Algebra Operations

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 


In [54]:
# np.linalg documentation
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    ``numpy.linalg``

    The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
    low level implementations of standard linear algebra algorithms. Those
    libraries may be provided by NumPy itself using C versions of a subset of their
    reference implementations but, when possible, highly optimized libraries that
    take advantage of specialized processor functionality are preferred. Examples
    of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
    are multithreaded and processor dependent, environmental variables and external
    packages such as threadpoolctl may be needed to control the number of threads
    or specify the processor architecture.

    - OpenBLAS: https://www.openblas.net/
    - threadpoolctl: https://github.com/joblib/threadpoolctl

    Please note that the most-used linear algebra functions in NumPy are present in
    the main ``nu

In [55]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [56]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

##### Rank of a matrix

In [57]:
np.linalg.matrix_rank(A)

np.int64(3)

##### Trace of matrix A

In [58]:
np.trace(A)

np.int64(11)

##### Determinant of a matrix

In [59]:
np.linalg.det(A)

np.float64(-306.0)

##### Inverse of matrix A

In [60]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [61]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [62]:
B = np.linalg.inv(A)

In [63]:
np.matmul(A,B) #actual matrix multiplication

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [64]:
A * B

array([[ 1.05882353, -0.00326797, -0.02287582],
       [ 0.23529412,  0.26143791,  0.4248366 ],
       [-0.23529412,  1.20261438,  0.36601307]])

##### Matrix A raised to power 3

In [65]:
np.linalg.matrix_power(A,3) # matrix multiplication A A A

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])