### NumPy Arrays

#### Creating Arrays

Let's import the NumPy library

In [1]:
import numpy as np

Let's create an empty NumPy array!

In [3]:
# empty_array = np.array() # This will throw an error

In [7]:
empty_array = np.array(object = []) # By default NumPy resorts to making a float64 array
empty_array

array([], dtype=float64)

In [9]:
type(empty_array) # data type of variable

numpy.ndarray

In [10]:
empty_array.dtype # data type of elements

dtype('float64')

In [11]:
empty_array.ndim # number of dimension

1

In [12]:
empty_array.shape # shape of the array

(0,)

In [13]:
empty_array.size # size of the array, counts all the elements across dimension

0

Let's create NumPy arrays with elements

In [15]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [16]:
type(my_array)

numpy.ndarray

In [17]:
my_array.dtype

dtype('int64')

In [18]:
my_array.ndim

1

In [19]:
my_array.shape

(3,)

In [20]:
my_array.size

3

In [22]:
my_array = np.array([1.5, 2, 3])
my_array

array([1.5, 2. , 3. ])

In [23]:
my_array.dtype

dtype('float64')

In [25]:
my_array = np.array(['yes', 'no', 'maybe'])
my_array

array(['yes', 'no', 'maybe'], dtype='<U5')

In [27]:
my_array.dtype # Unicode string datatype of length 5

dtype('<U5')

Here are some more ways to create NumPy arrays

In [28]:
# other way to create array
np.arange(start=1, stop=10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.array(range(1, 10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(start=1, stop=10, step=2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(-2, 10, 3)

array([-2,  1,  4,  7])

In [32]:
np.arange(10, 16)

array([10, 11, 12, 13, 14, 15])

In [33]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros(2)

array([0., 0.])

In [36]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.zeros(shape=10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones(shape=5, dtype='int')

array([1, 1, 1, 1, 1])

In [59]:
np.linspace(start=2, stop=3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [41]:
np.linspace(1, -5, 20)

array([ 1.        ,  0.68421053,  0.36842105,  0.05263158, -0.26315789,
       -0.57894737, -0.89473684, -1.21052632, -1.52631579, -1.84210526,
       -2.15789474, -2.47368421, -2.78947368, -3.10526316, -3.42105263,
       -3.73684211, -4.05263158, -4.36842105, -4.68421053, -5.        ])

We can create multidimensional NumPy arrays

In [43]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
type(matrix)

numpy.ndarray

In [45]:
matrix.dtype

dtype('int64')

In [46]:
matrix.ndim

2

In [47]:
matrix.size

9

In [49]:
threeD_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
threeD_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [50]:
type(threeD_array)

numpy.ndarray

In [51]:
threeD_array.dtype

dtype('int64')

In [52]:
threeD_array.ndim

3

In [53]:
threeD_array.shape

(2, 2, 2)

In [54]:
threeD_array.size

8

In [55]:
import numpy as np

# Creating a numpy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Initial shape of the array
print("Initial shape:", arr.shape)

# Changing the shape of the array
arr.shape = (2, 3)

# Array after reshaping
print("New shape:", arr.shape)
print("Reshaped array:\n", arr)

Initial shape: (6,)
New shape: (2, 3)
Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [57]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Indexing and Slicing Arrays

Let's import the numPy Library!

In [60]:
import numpy as np

In [61]:
my_array = np.array([1, 2, 3, 4, 5])

We can index and slice NumPy arrays like we can strings, lists and tuples

In [62]:
my_array[0]

np.int64(1)

In [63]:
my_array[4]

np.int64(5)

In [64]:
my_array[-1]

np.int64(5)

In [65]:
my_array[4:]

array([5])

In [66]:
my_array[:2]

array([1, 2])

In [67]:
my_array[::2]

array([1, 3, 5])

In [68]:
my_array[::-1]

array([5, 4, 3, 2, 1])

We can use boolean indexing to retrieve only those values we mark as True.
We can mark values in this way by using conditions

In [69]:
ages_list = [18, 15, 23, 14, 20]

In [70]:
# age_list >= 18 # cannot compare lists to integers

In [71]:
ages = np.array(ages_list)

In [72]:
type(ages)

numpy.ndarray

In [73]:
ages >= 18

array([ True, False,  True, False,  True])

In [74]:
ages[ages >= 18]

array([18, 23, 20])

In [78]:
ages[[True, False, True, False, True]]

array([18, 23, 20])

We can use 'fancy indexing' to select only certain items by index from a NumPy array

In [75]:
my_array[[4, 0, 1]]

array([5, 1, 2])

In [79]:
my_array

array([1, 2, 3, 4, 5])

In [80]:
my_array[[4, 0, 0, 0]]

array([5, 1, 1, 1])

We can use np.where() to get the indices where the elements within a NumPy array meet a condition

In [77]:
indices = np.where(my_array % 2 == 0)
indices

(array([1, 3]),)

In [81]:
my_array[indices]

array([2, 4])

We can use np.where() to modify NumPy arrays

In [82]:
np.where(my_array > 2, 100, my_array)

array([  1,   2, 100, 100, 100])

In [83]:
my_array

array([1, 2, 3, 4, 5])

In [85]:
new_array = np.where(my_array < 4, my_array ** 2, -55)
new_array

array([  1,   4,   9, -55, -55])

We can also directly modify NumPy arrays using subscripts

In [87]:
my_array_2 = my_array # making a shallow copy of my_array
my_array_2

array([1, 2, 3, 4, 5])

In [88]:
my_array_2[my_array_2 > 2] = 100
my_array_2

array([  1,   2, 100, 100, 100])

In [89]:
my_array

array([  1,   2, 100, 100, 100])

In [90]:
my_array = np.array([1, 2, 3, 4, 5])

In [92]:
my_array_3 = my_array.copy() # make a deep copy
my_array_3

array([1, 2, 3, 4, 5])

In [93]:
my_array_3[my_array_3  > 2] = 200
my_array_3

array([  1,   2, 200, 200, 200])

In [95]:
my_array # my_array is a deep copy, therefore my_array was not mofified

array([1, 2, 3, 4, 5])

We can slice multidimensional arrays by using commas in subscripts

In [99]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
matrix[1][2]

np.int64(6)

In [101]:
matrix[1, 2]

np.int64(6)

In [102]:
matrix[matrix > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

Let's create a simple 3D array to index and slice

In [103]:
arr_3D = np.array([
    [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
    [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
    [[18, 19, 20], [21, 22, 23], [24, 25, 26]]
])

In [104]:
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

How could we extract the element at the first layer of depth, in the second row, and in the third column!

In [106]:
arr_3D[0, 1, 2]

np.int64(5)

Let's slice to find the elements at the first two levels of depth, in the first tow rows, and in the first two columns

In [107]:
arr_3D[:2, :2, :2] 

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

Let's use integer indexing to index elements at (0, 0, 0), (1, 1, 1), and (2, 2, 2)

In [108]:
arr_3D > 15

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [109]:
arr_3D[arr_3D > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26])

In [110]:
np.where(arr_3D > 15, arr_3D, np.nan)

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [111]:
np.where(arr_3D > 15)

(array([1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [112]:
arr_3D[np.where(arr_3D > 15)]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [115]:
arr_3D[:,0,:]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [114]:
arr_3D[:,1,:]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [116]:
arr_3D[...,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [117]:
arr_3D[0,...]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

In [128]:
my_array.ndim

2

In [129]:
my_array[0, :]

array([1, 2, 3])

In [130]:
my_array[1:3, 2:4]

array([[6]])

In [131]:
my_array.ndim

2

In [132]:
my_array = np.array([1, 2, 3, 4, 5])

In [135]:
my_array[2 :]

array([3, 4, 5])

In [136]:
my_array[2:len(arr)]

array([], dtype=int64)

In [138]:
my_array[2] and my_array[:]

array([1, 2, 3, 4, 5])

In [139]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

In [140]:
arr[1:, 1:]

array([[ 60,  70,  80],
       [100, 110, 120],
       [140, 150, 160]])

In [141]:
arr[[1, 2], [1, 2]]

array([ 60, 110])

In [142]:
arr[1:3, -3:-1]

array([[ 60,  70],
       [100, 110]])

In [143]:
arr[1:-1, 1:-1]

array([[ 60,  70],
       [100, 110]])

In [144]:
arr[1:3, 1:3]

array([[ 60,  70],
       [100, 110]])

#### Array Manipulations

In [145]:
import numpy as np

In [160]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [161]:
arr = np.append(arr=arr, values=6) # append 6 to the end of the array
arr

array([1, 2, 3, 4, 5, 6])

In [162]:
arr = np.delete(arr = arr, obj=4) # delete the element at index 4
arr

array([1, 2, 3, 4, 6])

In [176]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
mat2 = np.append(mat , [10, 11, 12])
mat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [178]:
mat4 = np.append(mat, [[10, 11, 12]], axis=0)
mat4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [179]:
mat5 = np.append(mat, [[10], [11], [12]], axis=1)
mat5

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [180]:
mat6 = np.delete(mat, 1) # delete item at index 1
mat6

array([1, 3, 4, 5, 6, 7, 8, 9])

In [183]:
mat7 = np.delete(mat, 1, axis=0)
mat7

array([[1, 2, 3],
       [7, 8, 9]])

In [185]:
mat8 = np.delete(mat, 1, axis=1)
mat8

array([[1, 3],
       [4, 6],
       [7, 9]])

In [186]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

In [187]:
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [188]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [189]:
np.concatenate((arr1, arr2, arr))

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 6])

In [190]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[7, 8], [9, 10]])
d = np.array([[11, 12], [13, 14]])

In [191]:
np.concatenate((a, b), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [192]:
np.concatenate((a, b), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [193]:
np.concatenate((c, d), axis = 0)

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [194]:
np.concatenate((c, d), axis = 1)

array([[ 7,  8, 11, 12],
       [ 9, 10, 13, 14]])

#### Reshaping NumPy Array

In [201]:
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'])
arr.size

6

In [209]:
np.reshape(arr, (2, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [210]:
np.reshape(arr, (1, 1, 6))

array([[['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']]], dtype='<U6')

In [211]:
arr = np.array([[1, 2], [3, 4]])

In [212]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [213]:
np.transpose(arr, (1, 0))

array([[1, 3],
       [2, 4]])

In [214]:
np.transpose(arr).shape

(2, 2)

#### Broadcasting

In [215]:
import numpy as np

Broadcasting allows you to perform element-wise operations without the need for explicit looping

In [217]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [218]:
lst = [1, 2, 3, 4, 5]
lst

[1, 2, 3, 4, 5]

In [219]:
arr + 10

array([11, 12, 13, 14, 15])

In [222]:
# lst + 10

In [223]:
[x + 10 for x in lst]

[11, 12, 13, 14, 15]

In [224]:
arr ** 3

array([  1,   8,  27,  64, 125])

In [225]:
[x ** 3 for x in lst]

[1, 8, 27, 64, 125]

imagine you have following data which you want to feed into a machine learning algorithm

In [226]:
data = np.array([
    [25, 50000, 4.5, 1, 0],
    [45, 80000, 12.2, 0, 1],
    [35, 60000, 5, 1, 1]
])
data

array([[2.50e+01, 5.00e+04, 4.50e+00, 1.00e+00, 0.00e+00],
       [4.50e+01, 8.00e+04, 1.22e+01, 0.00e+00, 1.00e+00],
       [3.50e+01, 6.00e+04, 5.00e+00, 1.00e+00, 1.00e+00]])

In [229]:
# Scaling just the first three elements in each row
data[:, :3] = (data[:, :3] - data[:, :3].mean()) / data[:, :3].std() # standardising by subtracting the mean and dividing by the standard division
data

array([[-0.68725673,  0.94048486, -0.68792444,  1.        ,  0.        ],
       [-0.68660531,  1.91761838, -0.68767364,  0.        ,  1.        ],
       [-0.68693102,  1.26619603, -0.68790815,  1.        ,  1.        ]])

Broadcasting also allows you to perform operations between arrays of different shapes, as long as they follow NumPy's broadcasting rules

In [232]:
mat = np.array([[10, 20, 30], [40, 50, 60]])
mat

array([[10, 20, 30],
       [40, 50, 60]])

In [234]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [235]:
mat + arr

array([[11, 22, 33],
       [41, 52, 63]])

In [236]:
mat = np.array([[1, 2], [2, 3], [3, 4]])
mat.sum(axis = 1)

array([3, 5, 7])

In [237]:
import pandas as pd

In [239]:
s = pd.Series([1, 2, 3, None, 5])
s.isna()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [240]:
a = 'Hello'
b = 'World'
print(a + b, '!')

HelloWorld !


In [242]:
a = 18
b = 5
print(a % b)

3


In [243]:
theme_song = 'I wanna be the very best, like no one ever was. To catch them is my real test, to train them is my cause.'

In [244]:
theme_song.strip()

'I wanna be the very best, like no one ever was. To catch them is my real test, to train them is my cause.'